@startuml
'https://plantuml.com/sequence-diagram

autonumber
Actor Utilisateur
Utilisateur -> Contrôleur: Cliquer sur "Mot de passe oublié"
Contrôleur -> Contrôleur: Afficher la page de \n  réinitialisation du mot de passe
Utilisateur -> Contrôleur: Saisir les informations
Contrôleur -> Contrôleur: Vérifier que les informations ne sont pas vides
alt Vérification réussie
Contrôleur -> Service: Appeler la méthode \n  pour transférer les informations \n  au niveau du service
Service -> Mapper: Transférer les paramètres au niveau du mapper
Mapper -> BDD: Rechercher les informations correspondantes \n  dans la table enseignants
BDD --> Mapper: Retourner les résultats de la recherche
Mapper --> Service: Recevoir l'objet de recherche du mapper
Service --> Contrôleur: Renvoyer les résultats \n  de la recherche au Contrôleur
alt Résultats correspondants
Contrôleur -> Service: Transférer le nouveau mot de passe
Service -> Mapper: Transférer le nouveau mot de passe
Mapper -> BDD: Enregistrer le nouveau mot de passe
Contrôleur -> Utilisateur: L'utilisateur reçoit le nouveau mot de passe par email
else Résultats non correspondants
Contrôleur -> Contrôleur: Afficher une fenêtre pop-up d'alerte \n  que les informations ne correspondent pas
end
else Échec de la vérification
Contrôleur -> Contrôleur: Afficher une fenêtre pop-up d'alerte \n  que les informations ne correspondent pas
end
@enduml